travis:
  secure:
    BINSTAR_TOKEN: KMykjSpQZOjzyQEguqZF8azpRPvC2k4MYrtPnIpTk5d6sp/qh7/3fx1HCjodGhI2fQS98+pWH5pLQAOfK2riYhULwepokHv38daLk33pqXwMpFB6hhYKM0LxAErgNN3zzp0Vf8P5NyMXt22ez73ZmmdaKKnEBC3h8qLgnx6ITxiJRdaV5NWw0OtZiG2YLwmpKDsM8EST0v2GnlZdKnuUY37BYh0IES1u1gCuVoInGRpP1bx+Yx5sBq4y6OKcKz8i3K53Jc3X52mr+9l44gWYwoIz2xe/4odv5lPPfk2w37WWQIXs5fLi8by49JSli4iaWo8fvQod4Fca8JpSFdGeFO/gJy0a8Q/JQKOh6TbQLSi77S0K0lsEXWlclDudOFhGXrEeKcpyihgmoaUr3G2KwPcvEzscwzq71Oxj5r6y2OGfi9mxMh5hfWCDjAnG3vdU6mXO8JjeG/RHHTLEATgp8ESXli4zIMs+MPRiTBSf6GetLm4A/d1/LckC9SW2xrxenAwrU1UTVN+7BnlAK+bEHnS9GhJVCwJgHkQReTeKoyWLRQMndG2DuSYFjggdxUkb5VkdPcA6CYJ3gxn9js+C4FE+EthlJ8ktAfq7QMhziurO0dnIjtdYJaW7tDEE7kt0pU2+lLPtnj5dDlWrVXttv7DT2jPmbtiUYk/hHa5B5pw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
