travis:
  secure:
    BINSTAR_TOKEN: SVfXOEjGe/wOe26jGFBOFM5G7Fpm926DjMgJTEzWL5P0UzRSNE5z5V27evM9O6wcon9V5fykxmuvjmZjxZqf/F2d4S7RWBrMTu3NF1wI0WcKpyUWNvzuz5P9rvoM/EwrzgaVq6AicW4vq2kxYGB71mRZc84JHzFxYWVIjGYTb+OunCtQNDg+rdowK4r3eIBX8Dk6NaIzeLdbe0PatuIZSPsS2S7etdaZjPjtiD2bSxp3qDgAb9IeAz5vJAleeZbGtaEwpTQbU20ajtM5Wyxo1T6IQsugC5fJDbmUyEsA6561uJbIQGfGY0lGsmfkYvhoN6HCyHSWHXFkU+xfzcg9bVdVZzMYEqpSTbGsY5O6GVStX+eczGLXkufWH0DJ3jQ36Xl3CGSRf+u5zEGOypIe720c9p0xjd3Uyo+CmXQWqQ/pVFqFRpb5pyGomi4S18014PN0yXkT6+YpwWNNx2/gDxwsDGubhY9Yv2q6XcP7KiDPlER1JHyVoUPR8l+hIVg4pK0QnsbsfXEV3by60ydk3wG31IycNamI7ktkvI6ZEpYSMt0iU/IvzHOsRh/8Cw8EP93YAJpmz6UmjLhRoEK4VSuPvaDDh9vceVqjSP/afw52mt2RyqoB60ForYMH+8v5bH2bVs+oWsDqx5z2hahFb5PTGavZk+0dTkrhfpo9Agc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
